**Write a NumPy program to implement following operation**

**1) To convert a list of numeric values into a one-dimensional NumPy
array**

In [6]:
import numpy as np

In [7]:
l = [23,8,18,29]
print("original list :",l)

a = np.array(l)
print("one-dimensional NumPy array :",a)

original list : [23, 8, 18, 29]
one-dimensional NumPy array : [23  8 18 29]


**2) To create a 3x3 matrix with values ranging from 2 to 10**

In [8]:
a2 = np.arange(2,11).reshape(3,3)
print("A2 :",a2)

a2 : [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**3) To append values at the end of an array**


In [9]:
a3 = np.append(a, [12,11])
print('Array after appending : ', a3)

Array after appending :  [23  8 18 29 12 11]


**4) To create another shape from an array without changing its data(3x2
to 2x3)**

In [15]:
a3 = np.array([[1,2],
               [3,4],
               [5,6]])
print("A3 :",a4)
print("\n Shape of A3 :",a4.shape)

a4 = a3.reshape(2,3)
print("\n A4 :",a4)
print("\n Shape of A4 :",a4.shape)

A3 : [[1 2 3]
 [4 5 6]]

 Shape of A3 : (2, 3)

 A4 : [[1 2 3]
 [4 5 6]]

 Shape of A4 : (2, 3)
